import tkinter as tk

window= tk.Tk()
window.title("John Axel De Leon Profile")
window.geometry("600x600")
window.resizable(True,True)
window.configure(bg = "#E6E6E6")
# window.rowconfigure(0, weight=1)
# window.columnconfigure(0, weight=1)

paper = tk.Frame(window, bg="#121F27")
paper.pack(fill="both",expand=True,padx=40,pady=18)
# label = tk.Label(paper, text ="", font=("poppins",18),fg="darkorange",bg="#121F27",anchor="w",height=1,width=100)
# label.pack(padx = 30, pady = 0)
label = tk.Label(paper, text = "Student Profile", font=("georgia",30,"bold",),fg="darkorange",bg="#121F27",anchor="center",height=2,width=100)
label.pack()
label = tk.Label(paper, text ="────────────────────────────────────────────────────────────────────", font=("poppins",18),fg="darkorange",bg="#121F27",anchor="w",height=1,width=100)
label.pack(padx = 30, pady = 0)
label = tk.Label(paper, text = "▶️Name: John Axel B. De Leon", font=("poppins",18),fg="darkorange",bg="#121F27",anchor="w",height=2,width=100)
label.pack(padx = 30, pady = 0)
label = tk.Label(paper, text = "▶️Age: 18 Years Old", font=("poppins",18),fg="darkorange",bg="#121F27",anchor="w",height=2,width=100)
label.pack(padx = 30, pady = 0)
label = tk.Label(paper, text = "▶️Course: BSIT", font=("poppins",18),fg="darkorange",bg="#121F27",anchor="w",height=2,width=100)
label.pack(padx = 30, pady = 0)
label = tk.Label(paper, text = "▶️Birthday: July 10, 2005", font=("poppins",18),fg="darkorange",bg="#121F27",anchor="w",height=2,width=100)
label.pack(padx = 30, pady = 0)
label = tk.Label(paper, text = "▶️Motto: ", font=("poppins",18),fg="darkorange",bg="#121F27",anchor="w",height=2,width=100)
label.pack(padx = 30, pady = 0)
label = tk.Label(paper, text = "Moving Slowly is Better, than not moving", font=("poppins",18,"italic"),fg="darkorange",bg="#121F27",anchor="w",height=0,width=100)
label.pack(padx = 40, pady = 15)
label = tk.Label(paper, text ="────────────────────────────────────────────────────────────────────", font=("poppins",18),fg="darkorange",bg="#121F27",anchor="w",height=1,width=100)
label.pack(padx = 30, pady = 0)
window.mainloop()